export const projects = [
  {
    title: 'Architecture',
    description: "COVID-19 Status is a free, open-source Android application that shows the current state of COVID-19 in India and the world. It has a beautiful, simple, fast, and responsive UI.",
    image: '/images/covid.jpg',
    tags: ['Java', 'XML', 'Firebase', 'Rest API'],
    source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    visit: 'https://project.vipuljha.com/covid/',
    id: 0,
    type: 'architecture',
  },
  {
    title: 'Modern House Design',
    description: "A conceptual design of a modern house that incorporates sustainable architecture principles.",
    image: '/images/modern_house.jpg',
    tags: ['SketchUp', 'AutoCAD', '3D Modeling'],
    source: 'https://github.com/user/modern-house-design',
    visit: 'https://project.vipuljha.com/modern-house/',
    id: 2,
    type: 'architecture',
  },
  {
    title: 'Urban Park Layout',
    description: "Design of an urban park that includes walking paths, playgrounds, and green spaces.",
    image: '/images/urban_park.jpg',
    tags: ['Landscape Design', 'AutoCAD'],
    source: 'https://github.com/user/urban-park-layout',
    visit: 'https://project.vipuljha.com/urban-park/',
    id: 3,
    type: 'architecture',
  },
  {
    title: 'Painting Portfolio',
    description: "A collection of my best paintings showcasing various styles and techniques.",
    image: '/images/painting_portfolio.jpg',
    tags: ['Acrylic', 'Watercolor', 'Oil Painting'],
    source: 'https://github.com/user/painting-portfolio',
    visit: 'https://project.vipuljha.com/painting-portfolio/',
    id: 4,
    type: 'painting',
  },
  {
    title: 'Abstract Art Series',
    description: "A series of abstract paintings that explore color and form.",
    image: '/images/abstract_art.jpg',
    tags: ['Abstract', 'Mixed Media'],
    source: 'https://github.com/user/abstract-art-series',
    visit: 'https://project.vipuljha.com/abstract-art/',
    id: 5,
    type: 'painting',
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Aquired new skills while trying not to catch COVID-19', },
  { year: 2021, text: 'Survived COVID-19 and got my first Job at Primebook.', },
  { year: 2022, text: 'Completed B.Tech in Information Technology.', },
  { year: 2023, text: 'Year under progress....', },
];