import React from "react";

export const projects = [
  {
    id: "academic_1",
    title: "Residential Complex Design Based on Double-Skin Facade",
    description:
      "An academic master's thesis project (2016) focused on designing a modern residential complex in Tehran with a double-skin facade system to enhance energy efficiency, comfort, and aesthetics. The design includes passive strategies such as natural ventilation, sound insulation, and green terraces to create a sustainable and livable environment. It emphasizes reduced energy consumption, serene indoor conditions, and a strong visual connection with nature.",
    details: {
      type: "Academic Project",
      role: "Individual Project",
      location: "Tehran",
      grade: "18.60/20",
      year: 2016,
      tools: ["Design Builder", "3ds Max", "Photoshop", "Lumion"],
      key_achievement:
        "Demonstrated passive design strategies for energy reduction",
    },
    tags: [
      "Architecture",
      "Residential",
      "Academic",
      "Double-Skin Facade",
      "Energy Efficiency",
      "Sustainability",
    ],
    images: [
      "/images/Artboard 1.png",
      "/images/Artboard 2.png",
      "/images/Artboard 3.png",
      "/images/Artboard 4.png",
      "/images/Artboard 5.png",
    ],
  },
  {
    id: "academic_2",
    title: "Re-Design of Abandoned Factory into Innovation Hub",
    description:
      "An academic individual project (2015) focused on transforming an abandoned factory in Qazvin into an Innovation Hub that promotes creativity, collaboration, and sustainability. The design preserves the industrial character of the original architecture while integrating modern spaces such as co-working areas, maker labs, and community event zones. It reflects a strong emphasis on urban regeneration and adaptive reuse.",
    details: {
      type: "Academic Project",
      role: "Individual Project",
      location: "Qazvin",
      grade: "18/20",
      year: 2015,
      tools: ["AutoCAD", "3ds Max", "Photoshop", "Lumion"],
      key_achievement:
        "Integrated technological needs with historical architecture",
    },
    tags: [
      "Architecture",
      "Urban Regeneration",
      "Academic",
      "Adaptive Reuse",
      "Innovation Hub",
      "Sustainability",
    ],
    images: [
      "/images/Artboard 1-1.png",
      "/images/Artboard 2-1.png",
      "/images/Artboard 3-1.png",
      "/images/Artboard 4-1.png",
      "/images/Artboard 5-1.png",
    ],
  },
  {
    id: "academic_3",
    title: "Cultural Passage Design: Landscape & Urban Planning",
    description:
      "An academic individual project (2015) aimed at designing a cultural passage that fosters connectivity, cultural engagement, and urban vitality. The project integrates landscape architecture with urban planning principles to enhance quality of life and promote social interaction. Cultural passages in this design serve as active public spaces for exhibitions, art installations, and community gatherings, all rooted in sustainability and cultural identity.",
    details: {
      type: "Academic Project",
      role: "Individual Project",
      year: 2015,
      grade: "17.25/20",
      tools: [],
      key_achievement:
        "Integrated cultural programming with sustainable urban design",
    },
    tags: [
      "Urban Design",
      "Landscape Architecture",
      "Cultural Space",
      "Sustainability",
      "Public Realm",
      "Academic",
    ],
    images: [
      "/images/Artboard 1-2.png",
      "/images/Artboard 2-2.png",
      "/images/Artboard 3-2.png",
      "/images/Artboard 4-2.png",
      "/images/Artboard 5-2.png",
    ],
  },
  {
    id: "academic_4",
    title: "Parametric Design of Contemporary Art Museum",
    description:
      "An academic individual project (2013) that explores the use of parametric design in redefining the spatial and experiential qualities of a contemporary art museum. The design aims to create a flexible and adaptive environment that supports diverse exhibition formats and encourages interaction, discovery, and user engagement through dynamic spatial sequences.",
    details: {
      type: "Academic Project",
      role: "Individual Project",
      year: 2013,
      grade: "20/20",
      tools: ["Parametric Design Tools", "3D Modeling"],
      key_achievement:
        "Applied parametric design to enhance spatial experience and adaptability in a museum context",
    },
    tags: [
      "Architecture",
      "Parametric Design",
      "Museum",
      "Contemporary Art",
      "User Experience",
      "Academic",
    ],
    images: [
      "/images/Artboard 1-3.png",
      "/images/Artboard 2-3.png",
      "/images/Artboard 3-3.png",
      "/images/Artboard 4-3.png",
      "/images/Artboard 5-3.png",
    ],
  },
  {
    id: "residential_2024",
    title: "Residential Complex Design – 2024",
    description:
      "A company-based architectural project developed in collaboration with a design team in 2024. The residential complex is defined by its modular, stepped form and generous green terraces that create semi-private outdoor spaces. The design emphasizes natural daylight, cross-ventilation, and spatial diversity through an adaptive layout strategy. The composition offers a dynamic urban facade while improving living quality for its residents.",
    type: "architecture",
    tags: [
      "Residential",
      "Revit",
      "3ds Max",
      "Rhino",
      "Photoshop",
      "Lumion",
      "Teamwork",
      "2024",
    ],
    images: [
      "/images/1residential-2024.jpg",
      "/images/2residential-2024.png",
      "/images/3residential-2024.jpg",
      "/images/4residential-2024.jpg",
      "/images/5residential-2024.jpg",
      "/images/6residential-2024.jpg",
      "/images/7residential-2024.jpg",
      "/images/8residential-2024.jpg",
      "/images/9residential-2024.png",
      "/images/10residential-2024.png",
    ],
    details: {
      year: 2024,
      role: "Team Member",
      tools: ["Revit", "3ds Max", "Rhino", "Photoshop", "Lumion"],
    },
  },
  {
    id: "commercial_2023",
    title: "Office & Commercial Building Design – 2023",
    description:
      "This project was developed in 2023 as part of a company-based design team. The aim was to explore three different architectural alternatives for a mixed-use office and commercial building on a compact urban site. Each alternative proposes a unique massing strategy and spatial organization—ranging from curved, organic forms to modular, cubic compositions and minimalist monolithic designs. The goal was to balance aesthetic diversity, urban presence, and functional clarity in all three schemes.",
    type: "architecture",
    tags: [
      "Office",
      "Commercial",
      "Revit",
      "3ds Max",
      "Rhino",
      "Photoshop",
      "Lumion",
      "Concept Design",
      "Teamwork",
      "2023",
    ],
    images: [
      "/images/alt1-1.jpg",
      "/images/alt1-2.jpg",
      "/images/alt1-3.jpg",
      "/images/alt1-4.jpg",
      "/images/alt2-1.jpg",
      "/images/alt2-4.jpg",
      "/images/alt2-5.jpg",
      "/images/alt2-6.jpg",
      "/images/alt2-7.jpg",
      "/images/alt3-1.jpg",
      "/images/alt3-2.jpg",
      "/images/alt3-3.jpg",
      "/images/alt3-4.jpg",
      "/images/alt3-5.jpg",
    ],
    details: {
      year: 2023,
      role: "Team Member",
      tools: ["Revit", "3ds Max", "Rhino", "Photoshop", "Lumion"],
    },
  },
  {
    id: "ankara_renovation_2022",
    title: "Residential Renovation in Ankara – 2022",
    description:
      "A full-scale residential renovation project in Ankara, Turkey. The scope included interior redesign, material selection and procurement, construction supervision, and final furnishing. The goal was to enhance spatial quality and modernize the interior finishes while maintaining functionality and comfort for the residents. The process covered both architectural and executional phases, from concept to final styling.",
    type: "architecture",
    tags: [
      "Interior Design",
      "Renovation",
      "Material Selection",
      "Project Management",
      "Furniture Sourcing",
      "2022",
    ],
    images: ["/images/ankara-renovation1.jpg"],
    details: {
      year: 2022,
      role: "Lead Designer",
      location: "Ankara, Turkey",
      tools: ["AutoCAD", "3ds Max", "Photoshop"],
    },
  },
  {
    id: "ankara_luxury_2022",
    title: "Luxury Interior Design in Ankara – 2022",
    description:
      "An interior design and decoration project located in Ankara, Turkey, focused on luxury detailing. The project involved selecting and applying gold leaf finishes, custom wall framing, material procurement, and full interior furnishing. It combined elegance with functionality, from concept to final styling, including furniture selection and accessory coordination.",
    type: "architecture",
    tags: [
      "Interior Design",
      "Luxury Design",
      "Gold Leaf Application",
      "Material Selection",
      "Furniture Selection",
      "2022",
    ],
    images: [
      "/images/ankara1.JPEG",
      "/images/ankara2.JPEG",
      "/images/ankara3.JPEG",
      "/images/ankara4.JPEG",
      "/images/ankara5.JPEG",
      "/images/ankara6.JPEG",
      "/images/ankara7.JPEG",
      "/images/ankara8.JPEG",
      "/images/ankara9.JPEG",
      "/images/ankara10.JPEG",
      "/images/ankara11.JPEG",
      "/images/ankara12.JPEG",
      "/images/ankara13.JPEG",
      "/images/ankara14.JPEG",
      "/images/ankara15.JPEG",
      "/images/ankara16.JPEG",
      "/images/ankara17.JPEG",
      "/images/ankara18.JPEG",
    ],
    details: {
      year: 2022,
      role: "Lead Designer",
      location: "Ankara, Turkey",
      tools: ["AutoCAD", "3ds Max", "Photoshop"],
    },
  },
  {
    id: "tehran_renovation_2021",
    title: "Residential Renovation in Tehran – 2021",
    description:
      "A home renovation project in the Shahrak-e Gharb neighborhood of Tehran. The project involved full interior refurbishment, spatial reorganization, and updating finishes. The aim was to transform an outdated space into a modern, functional, and aesthetically pleasing living environment tailored to the client's needs.",
    type: "architecture",
    tags: [
      "Interior Design",
      "Renovation",
      "Residential",
      "Material Selection",
      "2021",
    ],
    images: [
      "/images/shahrak1.jpg",
      "/images/shahrak2.jpg",
      "/images/shahrak3.jpg",
      "/images/shahrak4.jpg",
    ],
    details: {
      year: 2021,
      role: "Lead Designer",
      location: "Tehran, Iran",
      tools: ["AutoCAD", "3ds Max", "Photoshop"],
    },
  },
  {
    title: "Residential Façade Design – Tehran (Gisha) – 2020",
    description:
      "A residential façade design project located in the Gisha neighborhood of Tehran, completed in 2020. The design aimed to modernize the building's appearance using a clean composition of wood-like panels and white plaster volumes. Emphasis was placed on proportion, rhythm, and creating a balanced visual identity suited to the urban context.",
    images: ["/images/1.jpg"],
    tags: [
      "Façade Design",
      "Residential",
      "Exterior Design",
      "3D Visualization",
      "2020",
    ],
    source: null,
    visit: null,
    id: 5,
  },
  {
    id: "gisha_renovation_2020",
    title: "Residential Renovation in Tehran (Gisha) – 2020",
    description:
      "This renovation project focused on transforming a residential apartment in Gisha, Tehran. The design featured custom ceiling lighting, curved openings, and elegant wall textures. The process included complete 3D interior design, material selection, and on-site execution with detailed plasterwork and lighting integration. Before-and-after visuals illustrate the design-to-construction workflow.",
    type: "architecture",
    tags: [
      "Interior Design",
      "Renovation",
      "3D Design",
      "Construction Supervision",
      "Tehran",
      "2020",
    ],
    images: ["/images/3-1.jpg", "/images/3-2.jpg"],
    details: {
      year: 2020,
      role: "Lead Designer",
      location: "Tehran, Iran",
      tools: ["AutoCAD", "3ds Max", "Photoshop"],
    },
  },
  {
    id: "yousefabad_salon_2020",
    title: "Beauty Salon Interior Design – Tehran (Yousef Abad) – 2020",
    description:
      "An interior design project for a beauty salon in Yousef Abad, Tehran. The space was designed to reflect elegance, comfort, and functionality. It includes custom lighting elements, modern furniture layouts, decorative partitions, and neutral materials to create a calm yet professional atmosphere. The project focused on user experience and space branding through cohesive spatial language.",
    type: "architecture",
    tags: [
      "Interior Design",
      "Commercial",
      "Beauty Salon",
      "Lighting Design",
      "Furniture Layout",
      "2020",
    ],
    images: ["/images/2.jpg"],
    details: {
      year: 2020,
      role: "Lead Designer",
      location: "Tehran, Iran",
      tools: ["AutoCAD", "3ds Max", "Photoshop"],
    },
  },
  {
    id: "urban_passage",
    title: "Urban Passage & Landscape Design – Master's Studio (Term 1)",
    description:
      "An academic landscape and urban design project developed during the first semester of the Master's program. The design was driven by the concept of 'Linear Urban Flow'—aiming to revitalize a continuous public corridor through pedestrian-oriented planning, integrated green pockets, and multifunctional urban nodes. The proposal emphasized social interaction, day/night activation, and environmental enhancement by reinforcing visual and spatial continuity along the corridor.",
    type: "architecture",
    tags: [
      "Urban Design",
      "Landscape Architecture",
      "Academic Project",
      "Linear Urban Flow",
      "Public Space",
      "Master's Studio",
      "Pedestrian Experience",
    ],
    images: ["/images/3.jpg", "/images/4.png", "/images/3.png"],
    details: {
      year: 2015,
      role: "Individual Project",
      type: "Academic Project",
      tools: ["AutoCAD", "3ds Max", "Photoshop"],
    },
  },
  {
    id: "entanglement_liberation",
    title: "Entanglement and Liberation",
    description:
      "Fluid motions and interwoven lines oscillate between control and chaos. The dynamic forms and contrasting colors depict a struggle between confinement and freedom—a moment of suspension where structure and disorder merge into one.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract",
      "Emotional Expression",
      "Painting",
    ],
    images: ["/images/a1.jpg"],
    details: {
      year: 2024,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "explosion_silence",
    title: "Explosion of Silence",
    description:
      "The splashes of color and chaotic lines evoke raw, uncontrolled energy. A moment of tranquility shattered—an eruption of motion in the midst of stillness.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract",
      "Emotional Expression",
      "Painting",
    ],
    images: ["/images/a2.jpg"],
    details: {
      year: 2024,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "unstable_connection",
    title: "Unstable Connection",
    description:
      "The combination of abstract forms and warm, neutral tones represents an attempt to find stability in an uncertain world.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract",
      "Geometric Forms",
      "Emotional Expression",
      "Painting",
    ],
    images: ["/images/a3.jpg"],
    details: {
      year: 2024,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "modern_chaos",
    title: "Modern Chaos",
    description:
      "The entangled lines, rigid structures, and contrasting colors reflect the fast-paced and industrialized modern world. A space where media, technology, and towering structures surround humanity, yet beneath the surface, a sense of disarray and uncertainty lingers.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract",
      "Geometric Forms",
      "Modern Life",
      "Painting",
    ],
    images: ["/images/a4.jpg"],
    details: {
      year: 2024,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "rooted_sand",
    title: "Rooted in the Sand",
    description:
      "Even if the branches are severed and no trunk remains, the roots persist in the soil. This piece echoes the story of the lone tree of Darak Beach—cut down, yet still alive in the memory of the land and deep within the sands. The scattered colors of sand and blood reflect the struggle between destruction and survival—a tale of an unbreakable bond with the earth.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract Landscape",
      "Symbolism",
      "Emotional Expression",
      "2023",
    ],
    images: ["/images/a5.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "yellow_memory",
    title: "The Scent of Yellow Memory",
    description:
      "A land of memories, where warm colors fade with time yet remain alive within. The groves, the river, childhood adventures—all take shape behind a haze of light and shifting textures, as if the grandmother's village still breathes within the colors. This piece reflects memories that, though blurred in detail, still hold their warmth.",
    type: "painting",
    tags: [
      "Acrylic",
      "Texture",
      "50×70 cm",
      "Abstract Landscape",
      "Nostalgia",
      "2023",
    ],
    images: ["/images/a6.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "fracture_time",
    title: "Fracture in Time",
    description:
      "A dividing line cuts through the canvas, marking a boundary between two dimensions of reality. Time seems to have paused—a moment between past and future, where nothing is certain.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract",
      "Conceptual",
      "Time & Space",
      "2023",
    ],
    images: ["/images/a7.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "weight_silence",
    title: "The Weight of Silence",
    description:
      "The somber hues and shadowy textures, paired with Eblehaj's poetry, evoke a sense of sorrow and contemplation. It feels as if the poet's words are lost within the abstract forms, inviting the viewer on an introspective journey between silence and whispers. This piece blends the gravity of unspoken emotions with the power of poetry.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract",
      "Persian Poetry",
      "Calligraphic Elements",
      "Emotional Depth",
      "2023",
    ],
    images: ["/images/a8.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "wind_memory",
    title: "Wind and Memory",
    description:
      "The flowing colors and fluid motion evoke a sense of movement and transformation. It feels as if the wind carries memories, reshaping them with every passing moment.",
    type: "painting",
    tags: ["Acrylic", "50×70 cm", "Abstract", "Movement", "Emotion", "2023"],
    images: ["/images/a9.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "rising_ashes",
    title: "Rising from Ashes",
    description:
      "The bold brushstrokes and interplay of cool and warm tones narrate a moment of transformation—the mythical Simorgh rising from ashes and wind. Its wings tear through the sky, leaving traces of wisdom and magic. Every drop of color echoes an ancient tale—one that still flows through time.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract",
      "Symbolism",
      "Simorgh",
      "Transformation",
      "2023",
    ],
    images: ["/images/a10.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "the_passage",
    title: "The Passage",
    description:
      "Two worlds stand on the edge of connection or separation—a fracture between two colors, two dimensions, two realities. This piece evokes the feeling of transition, where boundaries blur and change becomes inevitable. The heavy textures and contrasting hues intensify the tension and movement of this passage.",
    type: "painting",
    tags: [
      "Acrylic",
      "50×70 cm",
      "Abstract",
      "Color Contrast",
      "Transition",
      "2023",
    ],
    images: ["/images/a11.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "chiaroscuro_solitude",
    title: "Chiaroscuro of Solitude",
    description:
      "A world engulfed in darkness, where silence weighs heavier than any cry. Amidst the ruins, a faint yet unyielding light remains—not entirely lost, not fully revealed. This piece captures the moment of sinking into exhaustion and despair, yet wrestling internally to find a glimmer of light.",
    type: "painting",
    tags: [
      "Acrylic",
      "Texture",
      "50×70 cm",
      "Abstract",
      "Light and Dark",
      "Emotional Depth",
      "2023",
    ],
    images: ["/images/a12.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic on Canvas",
      dimensions: "50×70 cm",
    },
  },
  {
    id: "knots_identity",
    title: "Knots of Identity",
    description:
      "A mysterious gaze in search of hidden meaning. Aged textures and whispers of time are woven together in this fusion of tradition and modernity. The artwork embodies identity, time, and emotion—an interwoven dialogue between the past and the present, crafted through the threads of art. The use of a Persian carpet as canvas transforms history into a tangible element of contemporary expression.",
    type: "painting",
    tags: [
      "Acrylic",
      "Rug Painting",
      "Mixed Media",
      "Conceptual Art",
      "Cultural Identity",
      "2023",
    ],
    images: ["/images/art/knots-of-identity.jpg"],
    details: {
      year: 2023,
      medium: "Mixed Media on Persian Carpet",
      dimensions: "Variable",
    },
  },
  {
    id: "witnesses_silence",
    title: "Witnesses of Silence",
    description:
      "A constellation of eyes floats in a textured sea of handwritten poetry—verses of Ahmad Shamlou that whisper truths lost in noise. Each eye tells a story of witnessing, of presence, of silent observation. The painting becomes a canvas of layered consciousness, where personal identity merges with poetic resistance and memory.",
    type: "painting",
    tags: [
      "Acrylic",
      "Poetry-Inspired",
      "Shamlou",
      "Symbolism",
      "2021",
      "Eyes",
      "Mixed Media",
    ],
    images: ["/images/13.jpg"],
    details: {
      year: 2021,
      medium: "Mixed Media on Canvas",
      dimensions: "Variable",
    },
  },
  {
    id: "liberation_lostness",
    title: "Liberation or Lostness?",
    description:
      "It seems as if the boundary between reality and illusion is being torn apart. The figure, being drawn into the crimson curtain, represents an attempt to transcend the familiar and step into the unknown. This piece raises a question: What awaits beyond this veil—liberation or oblivion?",
    type: "painting",
    tags: ["Oil Painting", "Figurative", "Emotional", "Surreal", "Mystery"],
    images: ["/images/oil1.jpg"],
    details: {
      year: 2023,
      medium: "Oil on Canvas",
      dimensions: "120×80 cm",
    },
  },
  {
    id: "requiem_silence",
    title: "A Requiem in Silence",
    description:
      "A face dissolving into shadows and light, eyes that seem to witness something beyond the present—this piece, inspired by Requiem for a Dream, captures a sense of surrender, isolation, and the slow descent into emptiness. The flowing hair merges into the background like a stream of time and memories, consuming the figure in its wake.",
    type: "painting",
    tags: [
      "Oil Painting",
      "Figurative",
      "Emotional",
      "Minimalist",
      "Conceptual",
    ],
    images: ["/images/oil2.jpg"],
    details: {
      year: 2023,
      medium: "Oil on Canvas",
      dimensions: "120×80 cm",
    },
  },
  {
    id: "classic_women",
    title: "Classic Women Portraits",
    description:
      "A pair of classical oil paintings portraying feminine grace and poise. The first image captures a woman in an elegant pose with a glass of wine and cigarette, evoking a sense of noir nostalgia. The second depicts a dancer wrapped in a flowing red fabric, frozen in a moment of expressive movement. Executed in oil on canvas (100×80 cm), these works blend dramatic light, rich color, and timeless emotional presence.",
    type: "painting",
    tags: ["Oil Painting", "Classical", "Figurative", "Emotional", "Portrait"],
    images: ["/images/11.jpg"],
    details: {
      year: 2023,
      medium: "Oil on Canvas",
      dimensions: "100×80 cm",
    },
  },
  {
    id: "commercial_collection",
    title: "Contemporary Commercial Collection",
    description:
      "A curated set of contemporary artworks created for commercial and decorative spaces. These paintings blend abstraction, texture, and metallic elements to create visually striking compositions suitable for modern interiors. The use of gold foil, monochrome palettes, and rhythmic patterns invites elegance and energy into any setting. Mixed sizes and acrylic techniques make this a versatile and cohesive series.",
    type: "painting",
    tags: ["Acrylic", "Contemporary", "Abstract", "Commercial", "Decorative"],
    images: ["/images/a1-1.jpg"],
    details: {
      year: 2023,
      medium: "Acrylic with Mixed Media",
      dimensions: "Variable",
    },
  },
];

export const TimeLineData = [
  { year: 2016, text: "Started my journey as a developer." },
  { year: 2017, text: "Worked intensively on ROMs & Kernels." },
  { year: 2018, text: "Learned Android app development." },
  { year: 2019, text: "Finished Diploma in Computer Engineering." },
  { year: 2020, text: "Aquired new skills while trying not to catch COVID-19" },
  { year: 2021, text: "Survived COVID-19 and got my first Job at Primebook." },
  { year: 2022, text: "Completed B.Tech in Information Technology." },
  { year: 2023, text: "Year under progress...." },
];
